# Generated by manually reconstructing the missing migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
        migrations.AddField(
            model_name='invitation',
            name='token_hash',
            field=models.CharField(default='temp_hash', help_text='Hashed invitation token', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
