# Generated by Django 5.2.8 on 2025-11-28 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_add_organization_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organization",
            new_name="organizatio_is_acti_a02541_idx",
            old_name="org_active_created_idx",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["email", "status"], name="organizatio_email_b06ba1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["organization", "status"], name="organizatio_organiz_d73592_idx"
            ),
        ),
    ]
