# Generated by Django 5.2.8 on 2025-11-28 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_stripeevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stripeevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="stripeevent",
            name="subscriptions_type_proce_f96d2e_idx",
        ),
        migrations.RenameField(
            model_name="stripeevent",
            old_name="processed_at",
            new_name="created_at",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_5e8870_idx",
            old_name="sub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_current_e7d593_idx",
            old_name="sub_period_end_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_3d1ac5_idx",
            old_name="sub_status_period_idx",
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(
                fields=["type", "created_at"], name="subscriptio_type_2e8c77_idx"
            ),
        ),
    ]
