# Generated by Django 5.2.8 on 2025-11-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0004_rename_org_active_created_idx_organizatio_is_acti_a02541_idx_and_more",
        ),
        ("subscriptions", "0003_stripeevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stripeevent",
            new_name="subscriptio_type_48ef48_idx",
            old_name="subscriptions_type_proce_f96d2e_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_5e8870_idx",
            old_name="sub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_current_e7d593_idx",
            old_name="sub_period_end_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_3d1ac5_idx",
            old_name="sub_status_period_idx",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="organizations.organization",
            ),
        ),
    ]
