# Generated by Django 5.2.8 on 2025-11-28 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("users.new", "New Users"),
                            ("users.active", "Active Users"),
                            ("users.total", "Total Users"),
                            ("orgs.new", "New Organizations"),
                            ("orgs.active", "Active Organizations"),
                            ("orgs.total", "Total Organizations"),
                            ("subs.new", "New Subscriptions"),
                            ("subs.active", "Active Subscriptions"),
                            ("subs.cancelled", "Cancelled Subscriptions"),
                            ("revenue.mrr", "Monthly Recurring Revenue"),
                            ("revenue.arr", "Annual Recurring Revenue"),
                            ("revenue.new", "New Revenue"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "metric_type"],
                        name="analytics_d_date_576223_idx",
                    )
                ],
                "unique_together": {("date", "metric_type")},
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.login", "User Login"),
                            ("user.logout", "User Logout"),
                            ("user.register", "User Registration"),
                            ("user.password_change", "Password Changed"),
                            ("user.password_reset", "Password Reset"),
                            ("user.2fa_enabled", "2FA Enabled"),
                            ("user.2fa_disabled", "2FA Disabled"),
                            ("user.profile_update", "Profile Updated"),
                            ("org.created", "Organization Created"),
                            ("org.updated", "Organization Updated"),
                            ("org.deleted", "Organization Deleted"),
                            ("org.member_invited", "Member Invited"),
                            ("org.member_joined", "Member Joined"),
                            ("org.member_removed", "Member Removed"),
                            ("org.role_changed", "Member Role Changed"),
                            ("sub.created", "Subscription Created"),
                            ("sub.upgraded", "Subscription Upgraded"),
                            ("sub.downgraded", "Subscription Downgraded"),
                            ("sub.cancelled", "Subscription Cancelled"),
                            ("sub.renewed", "Subscription Renewed"),
                            ("sub.payment_failed", "Payment Failed"),
                            ("admin.user_impersonate", "User Impersonated"),
                            ("admin.user_suspend", "User Suspended"),
                            ("admin.user_activate", "User Activated"),
                            ("admin.data_export", "Data Exported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_a_created_b5efc6_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_a_user_id_abe786_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="analytics_a_action_8c93de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="analytics_u_user_id_a4851b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-last_activity"],
                        name="analytics_u_is_acti_aaf577_idx",
                    ),
                ],
            },
        ),
    ]
